### ISSUE TITLE
Graceful fallback when no formatprogram is present

### ISSUE THREAD

**Issue by ebellm** [Chiel92/vim-autoformat#167]
I have `au BufWrite * :Autoformat` set; I mostly edit python files.

Today I opened an HTML file in ViM 8.0.237.  I found that any time I saved it, all of the lines in the buffer would be deleted.  This was presumably because I did not have html-beautify installed; when I installed it, the problem disappeared.

Is it possible to check that formatprogram exists for the current filetype before running Autoformat to prevent this issue?

**Comment by Chiel92** [comment]
That should already be working that way. Please check first that you have the newest version of this plugin. Second, read[ this small paragraph](https://github.com/Chiel92/vim-autoformat#debugging) on providing debug info, and report back.

**Comment by Chiel92** [comment]
Any updates on this? Otherwise this issue will be closed.

**Comment by ebellm** [comment]
I confirmed that I'm running the newest version of the plugin by running `:PluginUpdate` under Vundle, and that the problem remains: the buffer is deleted if html-beautify is not installed.

The output of the messages window is:

```
Formatter htmlbeautify has errors: /bin/sh: html-beautify: command not found
 Skipping.
Failing config: 'html-beautify -f - -t'
Definition in 'g:formatdef_htmlbeautify' was unsuccessful.
"tmp.html" 1L, 1C written
```

(Also, the link to the debugging instructions is now https://github.com/Chiel92/vim-autoformat#it-doesnt-work)

**Comment by Chiel92** [comment]
That is weird though. I can't reproduce with Vim 7.4.
Btw, did you put any of the

```
let g:autoformat_autoindent = 0
let g:autoformat_retab = 0
let g:autoformat_remove_trailing_spaces = 0
```

commands in your vimrc?

**Comment by Chiel92** [comment]
Also, can you tell which python version is used to run vim-autoformat?

**Comment by ebellm** [comment]
Ah, yes--I have `let g:autoformat_autoindent = 0` in the vimrc.

My vim is built with Python 2.7.

**Comment by Chiel92** [comment]
Three more questions:

- Does it also happen when you don't have the autocmd BufWrite, but trigger `:Autoformat` manually?
- Do you also have the problem with other filetypes/formatters?
- To be sure, can you test the behaviour in an empty vimrc, with just vim-autoformat (and your plugin manager of course)?

**Comment by Chiel92** [comment]
Any updates on this?

**Comment by ebellm** [comment]
>  Does it also happen when you don't have the autocmd BufWrite, but trigger :Autoformat manually?

Yes.

> Do you also have the problem with other filetypes/formatters?

Not that I've seen.  I use the python autoformatter extensively day-to-day.

> To be sure, can you test the behaviour in an empty vimrc, with just vim-autoformat (and your plugin manager of course)?

The same problem occurs.

**Comment by Chiel92** [comment]
I can't make any sense of this. If I look at the code I don't see how you could have gotten the output

```
Formatter htmlbeautify has errors: /bin/sh: html-beautify: command not found
 Skipping.
Failing config: 'html-beautify -f - -t'
Definition in 'g:formatdef_htmlbeautify' was unsuccessful.
"tmp.html" 1L, 1C written
```

I would expect to have a line of `No format definitions were successful.` in there. I also can't tell why the buffer is emptied, as it doesn't go into the code path where the buffer is touched.

**Comment by Chiel92** [comment]
Closing as not reproducible. Feel free to share any further information. If the problem persists and you can find a consistent reproduction scenario that I can work with, I'd like to know.
